#!/usr/bin/groovy

node('master')
{
   println "Master";
}

node ('cmake-slave')
{
  println "cmake slave";

  stage('checkout')
  { 
    checkout scm
  }
  stage ('build')
  {
     sh "ls -lrt; pwd"
     sh "cmake ."
  }
}

