#!/usr/bin/groovy

node('master')
{
   println "Master";
}

node ('cmake-slave')
{
  println "cmake slave";

  stage('checkout')
  { 
    checkout scm
  }
  stage ('build')
  {
     dir("openshift-cplus-sample/cmake") {
       sh "ls -lrt; pwd"
       sh "cmake ."
    }
  }
}

